name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # 可以根据需要调整 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 确保路径正确

      - name: Run script
        run: python scripts/bbb/baba2.py

      - name: List files
        run: ls -la scripts/bbb/

      - name: Commit and push M3U files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add scripts/bbb/*.m3u || echo "No M3U files found to add"
          git commit -m "Add/update M3U files" || echo "No changes to commit"
          git push origin main
        if: success() && steps.run_script.outputs.new_files == 'true'
