name: Run Python Script

on:
  schedule:
    - cron: '0 16 * * *'  # 根据 UTC 时间，调整到本地午夜 0 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 虚拟环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
        
      - name: Run Python script
        run: python scripts/aaa/test1.py

      - name: Check for generated files
        run: |
          ls -la scripts/aaa/  # 列出目录中的所有文件，确认 M3U 文件是否存在

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and push M3U files
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add scripts/aaa/*.m3u
            git commit -m "Add generated M3U files"
            git push
          fi
