name: Run test.py Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 安装依赖（如果需要）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # 运行脚本
      - name: Run test.py
        run: |
          python ./scripts/ddd/test.py

      # 查看生成的 hao.txt 文件
      - name: Upload hao.txt as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: hao-txt
          path: ./scripts/ddd/hao.txt
