name: Sync Best Proxy IPs

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

  workflow_dispatch:  # 手动触发

jobs:
  update-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests library
      run: pip install requests

    - name: Run Python script to update proxy list
      run: python scripts/bbb/add_port_script.py  # 确保此路径和文件名与仓库中的一致

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add scripts/bbb/port.txt
        git commit -m "Update port.txt with port 443"
        git push
