name: Update Port List

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时触发一次

jobs:
  update-port:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run generate_port_txt.py to check IPs
      run: |
        python scripts/bbb/generate_port_txt.py  # 自动更新 port.txt 文件
