name: Update IP List

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # 每小时运行一次

jobs:
  update_ip_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      # 使用正确的脚本路径运行脚本
      - name: Run IP update script
        run: python scripts/bbb/add_port_script.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add scripts/bbb/port.txt
          git commit -m "Update IP list with port 443"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
