name: Update KXWL Files

on:
  schedule:
    - cron: "0 0,8,16 * * *"  # 每天的 12 AM、8 AM 和 4 PM 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-kxwl-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python script to sync files
      env:
        GITHUB_USER: "xinyex"
        GITHUB_REPO: "ks"
      run: |
        python scripts/ccc/update_ccc.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add scripts/ccc/kxwl.*
        git diff --quiet && git diff --staged --quiet || git commit -m "Update kxwl files with recent content"
        git push || echo "No changes to push"
